// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type DevelopmentHomePageDocumentDataSlicesSlice =
  | SplitTextBlockSlice
  | PlayerListSlice
  | VideoBlockSlice
  | TextBlockSlice;

/**
 * Content for Development Home Page documents
 */
interface DevelopmentHomePageDocumentData {
  /**
   * Slice Zone field in *Development Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: development_home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<DevelopmentHomePageDocumentDataSlicesSlice> /**
   * Meta Description field in *Development Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: development_home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Development Home Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: development_home_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Development Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: development_home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Robots field in *Development Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: development_home_page.meta_robots
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_robots: prismic.KeyTextField;
}

/**
 * Development Home Page document from Prismic
 *
 * - **API ID**: `development_home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DevelopmentHomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<DevelopmentHomePageDocumentData>,
    "development_home_page",
    Lang
  >;

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Text Field field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.text_field
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text_field: prismic.RichTextField;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HomePageDocumentDataSlicesSlice =
  | PlayerListSlice
  | TextBlockSlice
  | VideoBlockSlice;

/**
 * Content for Home Page documents
 */
interface HomePageDocumentData {
  /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice> /**
   * Meta Description field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

/**
 * Item in *Navigation → Menu Items*
 */
export interface NavigationDocumentDataMenuItemsItem {
  /**
   * Label field in *Navigation → Menu Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.menu_items[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Navigation → Menu Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.menu_items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Logo field in *Navigation*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Menu Items field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.menu_items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  menu_items: prismic.GroupField<Simplify<NavigationDocumentDataMenuItemsItem>>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

/**
 * Item in *Player → Player Stats*
 */
export interface PlayerCardDocumentDataPlayerStatsItem {
  /**
   * Stat Label field in *Player → Player Stats*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: player_card.player_stats[].stat_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  stat_label: prismic.KeyTextField;

  /**
   * Stat field in *Player → Player Stats*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: player_card.player_stats[].stat
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  stat: prismic.KeyTextField;
}

type PlayerCardDocumentDataSlicesSlice = never;

/**
 * Content for Player documents
 */
interface PlayerCardDocumentData {
  /**
   * Player Name field in *Player*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: player_card.player_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  player_name: prismic.KeyTextField;

  /**
   * Player Position field in *Player*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: player_card.player_position
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  player_position: prismic.KeyTextField;

  /**
   * Image field in *Player*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: player_card.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Player Stats field in *Player*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: player_card.player_stats[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  player_stats: prismic.GroupField<
    Simplify<PlayerCardDocumentDataPlayerStatsItem>
  >;

  /**
   * Short Bio field in *Player*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: player_card.short_bio
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  short_bio: prismic.KeyTextField;

  /**
   * Player Story field in *Player*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: player_card.player_story
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  player_story: prismic.RichTextField;

  /**
   * Player Type field in *Player*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: player_card.player_type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  player_type: prismic.SelectField<"Local" | "US">;

  /**
   * Player Video field in *Player*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: player_card.player_video
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  player_video: prismic.EmbedField;

  /**
   * Player Feature Image field in *Player*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: player_card.player_feature_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  player_feature_image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Player*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: player_card.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PlayerCardDocumentDataSlicesSlice> /**
   * Meta Title field in *Player*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: player_card.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Player*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: player_card.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;
}

/**
 * Player document from Prismic
 *
 * - **API ID**: `player_card`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PlayerCardDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PlayerCardDocumentData>,
    "player_card",
    Lang
  >;

type PlayerListingPageDocumentDataSlicesSlice = TextBlockSlice;

/**
 * Content for Player Listing Page documents
 */
interface PlayerListingPageDocumentData {
  /**
   * Slice Zone field in *Player Listing Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: player_listing_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PlayerListingPageDocumentDataSlicesSlice> /**
   * Meta Description field in *Player Listing Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: player_listing_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Player Listing Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: player_listing_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Player Listing Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: player_listing_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Robots field in *Player Listing Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: player_listing_page.meta_robots
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_robots: prismic.KeyTextField;
}

/**
 * Player Listing Page document from Prismic
 *
 * - **API ID**: `player_listing_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PlayerListingPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PlayerListingPageDocumentData>,
    "player_listing_page",
    Lang
  >;

export type AllDocumentTypes =
  | DevelopmentHomePageDocument
  | FooterDocument
  | HomePageDocument
  | NavigationDocument
  | PlayerCardDocument
  | PlayerListingPageDocument;

/**
 * Primary content in *PlayerList → Default → Primary*
 */
export interface PlayerListSliceDefaultPrimary {
  /**
   * Number of players to show field in *PlayerList → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: player_list.default.primary.number_of_players
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  number_of_players: prismic.NumberField;

  /**
   * Type Filter field in *PlayerList → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: player_list.default.primary.type_filter
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type_filter: prismic.SelectField<"Local" | "US">;

  /**
   * Player 1 field in *PlayerList → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: player_list.default.primary.player_1
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  player_1: prismic.ContentRelationshipField;

  /**
   * Player 2 field in *PlayerList → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: player_list.default.primary.player_2
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  player_2: prismic.ContentRelationshipField;

  /**
   * Player 3 field in *PlayerList → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: player_list.default.primary.player_3
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  player_3: prismic.ContentRelationshipField;

  /**
   * Player 4 field in *PlayerList → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: player_list.default.primary.player_4
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  player_4: prismic.ContentRelationshipField;
}

/**
 * Default variation for PlayerList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PlayerListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PlayerListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PlayerList*
 */
type PlayerListSliceVariation = PlayerListSliceDefault;

/**
 * PlayerList Shared Slice
 *
 * - **API ID**: `player_list`
 * - **Description**: PlayerList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PlayerListSlice = prismic.SharedSlice<
  "player_list",
  PlayerListSliceVariation
>;

/**
 * Primary content in *SplitTextBlock → Default → Primary*
 */
export interface SplitTextBlockSliceDefaultPrimary {
  /**
   * Heading One Eyebrow field in *SplitTextBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: split_text_block.default.primary.heading_one_eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading_one_eyebrow: prismic.KeyTextField;

  /**
   * Heading One field in *SplitTextBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: split_text_block.default.primary.heading_one
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading_one: prismic.RichTextField;

  /**
   * Body Content One field in *SplitTextBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: split_text_block.default.primary.body_content_one
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body_content_one: prismic.RichTextField;

  /**
   * Link One field in *SplitTextBlock → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: split_text_block.default.primary.link_one
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_one: prismic.LinkField;

  /**
   * Link Label One field in *SplitTextBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: split_text_block.default.primary.link_label_one
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_label_one: prismic.KeyTextField;

  /**
   * Heading Two Eyebrow field in *SplitTextBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: split_text_block.default.primary.heading_two_eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading_two_eyebrow: prismic.KeyTextField;

  /**
   * Heading Two field in *SplitTextBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: split_text_block.default.primary.heading_two
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading_two: prismic.RichTextField;

  /**
   * Body Content Two field in *SplitTextBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: split_text_block.default.primary.body_content_two
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body_content_two: prismic.RichTextField;

  /**
   * Link Two field in *SplitTextBlock → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: split_text_block.default.primary.link_two
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_two: prismic.LinkField;

  /**
   * Link Label Two field in *SplitTextBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: split_text_block.default.primary.link_label_two
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_label_two: prismic.KeyTextField;
}

/**
 * Default variation for SplitTextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SplitTextBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SplitTextBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SplitTextBlock*
 */
type SplitTextBlockSliceVariation = SplitTextBlockSliceDefault;

/**
 * SplitTextBlock Shared Slice
 *
 * - **API ID**: `split_text_block`
 * - **Description**: SplitTextBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SplitTextBlockSlice = prismic.SharedSlice<
  "split_text_block",
  SplitTextBlockSliceVariation
>;

/**
 * Primary content in *TextBlock → TextBlock → Primary*
 */
export interface TextBlockSliceDefaultPrimary {
  /**
   * Text Align field in *TextBlock → TextBlock → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: text-left
   * - **API ID Path**: text_block.default.primary.text_align
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  text_align: prismic.SelectField<"text-left" | "text-center", "filled">;

  /**
   * Title Field field in *TextBlock → TextBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.default.primary.title_field
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title_field: prismic.RichTextField;

  /**
   * Body Field field in *TextBlock → TextBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.default.primary.body_field
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body_field: prismic.RichTextField;
}

/**
 * TextBlock variation for TextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextBlockSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *TextBlock → TextBlock - WithButton → Primary*
 */
export interface TextBlockSliceTextBlockWithButtonPrimary {
  /**
   * Text Align field in *TextBlock → TextBlock - WithButton → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: text-left
   * - **API ID Path**: text_block.textBlockWithButton.primary.text_align
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  text_align: prismic.SelectField<"text-left" | "text-center", "filled">;

  /**
   * Title Field field in *TextBlock → TextBlock - WithButton → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.textBlockWithButton.primary.title_field
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title_field: prismic.RichTextField;

  /**
   * Body Field field in *TextBlock → TextBlock - WithButton → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.textBlockWithButton.primary.body_field
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body_field: prismic.RichTextField;

  /**
   * Button Link field in *TextBlock → TextBlock - WithButton → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.textBlockWithButton.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Button Label field in *TextBlock → TextBlock - WithButton → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.textBlockWithButton.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Testing Link field in *TextBlock → TextBlock - WithButton → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.textBlockWithButton.primary.testing_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  testing_link: prismic.LinkField;
}

/**
 * TextBlock - WithButton variation for TextBlock Slice
 *
 * - **API ID**: `textBlockWithButton`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSliceTextBlockWithButton = prismic.SharedSliceVariation<
  "textBlockWithButton",
  Simplify<TextBlockSliceTextBlockWithButtonPrimary>,
  never
>;

/**
 * Primary content in *TextBlock → TextBlock - WithImage  → Primary*
 */
export interface TextBlockSliceTextBlockWithImagePrimary {
  /**
   * Image field in *TextBlock → TextBlock - WithImage  → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.textBlockWithImage.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Body Field field in *TextBlock → TextBlock - WithImage  → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.textBlockWithImage.primary.body_field
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body_field: prismic.RichTextField;
}

/**
 * TextBlock - WithImage  variation for TextBlock Slice
 *
 * - **API ID**: `textBlockWithImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSliceTextBlockWithImage = prismic.SharedSliceVariation<
  "textBlockWithImage",
  Simplify<TextBlockSliceTextBlockWithImagePrimary>,
  never
>;

/**
 * Slice variation for *TextBlock*
 */
type TextBlockSliceVariation =
  | TextBlockSliceDefault
  | TextBlockSliceTextBlockWithButton
  | TextBlockSliceTextBlockWithImage;

/**
 * TextBlock Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: TextBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSlice = prismic.SharedSlice<
  "text_block",
  TextBlockSliceVariation
>;

/**
 * Primary content in *VideoBlock → Default → Primary*
 */
export interface VideoBlockSliceDefaultPrimary {
  /**
   * Title field in *VideoBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *VideoBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_block.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Video field in *VideoBlock → Default → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: video_block.default.primary.video
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  video: prismic.EmbedField;
}

/**
 * Default variation for VideoBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VideoBlock*
 */
type VideoBlockSliceVariation = VideoBlockSliceDefault;

/**
 * VideoBlock Shared Slice
 *
 * - **API ID**: `video_block`
 * - **Description**: VideoBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoBlockSlice = prismic.SharedSlice<
  "video_block",
  VideoBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      DevelopmentHomePageDocument,
      DevelopmentHomePageDocumentData,
      DevelopmentHomePageDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataMenuItemsItem,
      PlayerCardDocument,
      PlayerCardDocumentData,
      PlayerCardDocumentDataPlayerStatsItem,
      PlayerCardDocumentDataSlicesSlice,
      PlayerListingPageDocument,
      PlayerListingPageDocumentData,
      PlayerListingPageDocumentDataSlicesSlice,
      AllDocumentTypes,
      PlayerListSlice,
      PlayerListSliceDefaultPrimary,
      PlayerListSliceVariation,
      PlayerListSliceDefault,
      SplitTextBlockSlice,
      SplitTextBlockSliceDefaultPrimary,
      SplitTextBlockSliceVariation,
      SplitTextBlockSliceDefault,
      TextBlockSlice,
      TextBlockSliceDefaultPrimary,
      TextBlockSliceTextBlockWithButtonPrimary,
      TextBlockSliceTextBlockWithImagePrimary,
      TextBlockSliceVariation,
      TextBlockSliceDefault,
      TextBlockSliceTextBlockWithButton,
      TextBlockSliceTextBlockWithImage,
      VideoBlockSlice,
      VideoBlockSliceDefaultPrimary,
      VideoBlockSliceVariation,
      VideoBlockSliceDefault,
    };
  }
}
