// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  player_card: dynamic(() => import("./PlayerCard")),
  text_block: dynamic(() => import("./TextBlock")),
  video_block: dynamic(() => import("./VideoBlock")),
};
